language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
# Install dependencies
install:
    - "pip install -U ."
    - "sudo python download_corpora.py"
# Run tests
script: "python run_tests.py"
